package com.moolu.plugins.eps;

/**
 * Created by Nanan on 3/4/2015.
 */
public class TrusteerConstance {
    //Risk item name for query
    public final static String RISK_ITEM_TOTAL_RISK_GENERIC = "total.risk.generic";
    public final static String RISK_ITEM_TAS_CONFIG_UPDATE = "tas.config_update";
    public final static String RISK_ITEM_OS_VER_UP_TO_DATE = "os.ver_up_to_date";
    public final static String RISK_ITEM_OS_ROOTED = "os.rooted";
    public final static String RISK_ITEM_MALWARE_ANY = "malware.any";
    public final static String RISK_ITEM_APP_RESTRICT = "plat.android.apprestrict";
    public final static String RISK_ITEM_DUMPSYS = "plat.android.dumpsys";
    //TAS_CLIENT_INFO setting
    public final static String CLIENT_ID = "hsbc.bankingapp";
    public final static String CLIENT_KEY = "YMAQAABNFUWS2LKCIVDUSTRAKBKUETCJIMQEWRKZFUWS2LJNBJGUSSKCJFVECTSCM5VXC2DLNFDTS5ZQIJAVCRKGIFAU6Q2BKE4ECTKJJFBEGZ2LINAVCRKBNNETQTBQNM3U6N2DK5XEYNLFKVZVIU2XBI4XKUBYMVLWGRLCKY4VE3KIIRJU65DBN5FCWVJWJVRSWVDSPJRXOZSSOBREYNKXNQZGKSSPJNJUOVBRJYZECMTUJVWEGRDNNNRGWMDPBI2XOSLFJMVW4SKQOJWWOVZQIJWWKWKVJR2FCTTMMNHFKWCFGRWGE4TUI5GCWOLULJJHSRSLJB3WUY2HNZSDKWDDKBGHSRSII5CHK3CBBJFTO5ZVLIXS6ODJMNCEER2SKF3W2WSSJV2U45ZUJFGFGQ32NBHUCYKHKNIE6VCSOJ3HO32LJMXU6MTSMZDHE6TEGNLXU3KQI5IDO6TKBJTEI2TCHAZUIT2KNQ3HISRPONXGSTLNHA4W4ZKMMVDUUNKSKVNFEMLSNB4VSMLRJBYU4ZTKGNRDGSCTJFWUIULOGUYEYQJVNFZDKSZWBJ5C65JYF5DXAVLUMRMVIQKCMFXFAVCMJNQW6YKGNA3UIWTIGRZUEUTYHAZEC2LWKNMG6OJRMQ4HIRLGM5CG6WKDGMYTONBRGBWC6RZSBJJXOSKEIFIUCQQKFUWS2LJNIVHEIICQKVBEYSKDEBFUKWJNFUWS2LIKNKE6W67SJCNW5LTJMMYA4ZOKLM";
    public final static String VENDOR_ID = "moolu.com";
    public final static String COMMENT = "MooLu";
    //configure update mode in initiation
    public final static boolean IS_MANUAL_BACKGROUND_TASKS=false;
}
